/**/**:
  ros__parameters:


    ekf_verbosity: "DEBUG" # Options: SILENT, ERROR, WARNING, INFO, DEBUG, VERBOSE

    process_noise_gains:
      velocity: 0.00186
      orientation: 0.00018665
      accelerometer: 0.006
      gyroscope: 0.000038785

    measurement_noise_gains:
      px4_odometry:
        linear_velocity: 0.01
        angular_velocity: 0.001
      fast_lio:
        position: 0.001
        orientation: 0.01
        linear_velocity: 0.1
      imu:
        angular_velocity: 0.01
        
    limits:
      vio:
        position:
          x: 0.4
          y: 0.4
          z: 0.4
        orientation: 
          roll: 0.05
          pitch: 0.05
          yaw: 0.05