/**/**:
  ros__parameters:

    process_noise_gains:
      position: 0.1
      orientation: 0.01
      linear_velocity: 0.1
      angular_velocity: 0.1

    measurement_noise_gains:
      px4_odometry:
        linear_velocity: 0.01
        angular_velocity: 0.001
      fast_lio:
        position: 0.001
        orientation: 0.01
        linear_velocity: 0.1
      imu:
        angular_velocity: 0.01